### ISSUE TITLE
[micro-dash] Bug in kebabCase

### ISSUE THREAD

**Issue by luhis** [simontonsoftware/s-libs#110] opened 2023-09-12 07:25 UTC
Hi,

I have found a difference vs Lodash in the kebabCase function.

`kebabCase("2013 5th November")` gives `"2013-5th-november"` in Lodash, but `"2013-5-th-november"` in micro-dash.  It looks like a bug in the words function.  I've not looked into it much yet.

Matt

**Comment by ersimont** [comment] 2023-09-13 01:09
Thank you for caring about the library enough to open an issue!

This is expected behavior. It's documented in the readme under "[Differences from Lodash](https://github.com/simontonsoftware/s-libs/tree/master/projects/micro-dash#differences-from-lodash)":

> String functions are designed for simple cases like variable names. They only treat `[0-9A-Za-z]` as part of words and are not smart about contractions or ordinals (e.g. `I'll` or `1st`).

This is intentional because matching Lodash's string parsing is a slippery slope that ends in their regex file that looks like [this](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/.internal/unicodeWords.js). In the spirit of micro-dash, I made the decision to keep things simpler and smaller.

I'll close this ticket, but please feel free to argue for an exception in light of this. And I hope you find at least the rest of the library meets all your needs!

**Closed by ersimont** 2023-09-13 01:09 UTC
