### ISSUE TITLE
`WrappedFormControlSuperclass` validators not work

### ISSUE THREAD

**Issue by piotrGTX** [simontonsoftware/s-libs#82] opened 2022-08-27 09:43 UTC
Hello, I think I found a bug. 

"s-libs" version 14.0.0
"angular" version 14.0.7

I create component like this:

TS:

```
@Component({
  selector: 'app-input-number',
  templateUrl: './input-number.component.html',
  styleUrls: ['./input-number.component.scss'],
  providers: [provideValueAccessor(InputNumberComponent)]
})
export class InputNumberComponent extends WrappedFormControlSuperclass<number> {
  get showErrors(): boolean {
    return this.control.invalid && this.control.dirty
  }
}
```

HTML:
```
<input [formControl]="control" type="number" />
<div *ngIf="showErrors">
  <span *ngFor="let errorEntry of control.errors | keyvalue">{{ errorEntry | json }}</span>
</div>
```

USAGE:
```
this.formBuilder.group({
  share: this.formBuilder.control(0, {
    nonNullable: true,
    validators: [Validators.required, Validators.min(1), Validators.max(100)]
  }),
});
```

"control.errors" has always a null value 😢 I found solution -> reassign control in `ngAfterContentInit` in <app-input-number>
But maybe I do something wrong 💻 

SOLUTION:
```
  ngAfterContentInit(): void {
    const ctrl = this.injector.get(NgControl);
    ctrl.valueAccessor = this;
    this.control = ctrl.control as FormControl<InputType>;
  }
```

**Comment by ersimont** [comment] 2022-08-27 12:58
Ohhh interesting. You indeed found a bug, thank you for reporting it. To my surprise, I see that the timing of `formControlName` is different than `ngModel`. So I see the cause of the problem ... now to find a solution ...

**Comment by ersimont** [comment] 2022-08-27 13:39
This should be fixed in the next release (see commit linked by Git directly above

**Closed** 2022-08-27 13:39 UTC
